name: frontend_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.9
  flutter_animate: ^4.5.2

  cupertino_icons: ^1.0.8


  # Lottie Animations
  lottie: ^2.7.0
  
  # For better JSON
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  
  # Optional: For enhanced UI
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  
  # HTTP client for API calls
  http: ^1.2.0
  
  
  # Local storage for tokens
  shared_preferences: ^2.2.2
  
  # State management
  provider: ^6.1.1
   
  fl_chart: ^0.65.0          # For charts in monitoring screen
  intl: ^0.18.1              # For date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true